spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: 5ql@dmin2019

  batch:
    job:
      enabled: true
      names: userExportJob
