spring:
  # データベース接続文字列
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: 5ql@dmin2019
  # ジョブ名で実行制御
  batch:
    job:
      enabled: true
      #IDE実行時にジョブ名指定
      names: importJob

logging:
  level:
    jp.co.fly.model.mapper.PrefectureDao: debug
